name: ACS Build and Push Docker image to Docker Hub

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub runner
      - name: Check out the repo
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Clear Docker build cache
      - name: Clear Docker build cache
        run: docker builder prune --all --force

      # Build and push Docker image for Web client
      - name: Build and push Docker image Web client
        uses: docker/build-push-action@v4
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ampc-event-management-web:${{ github.event.release.tag_name }}

      # Build and push Docker image for Server
      - name: Build and push Server
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ampc-event-management-server:${{ github.event.release.tag_name }}
